version: "2"
linters:
  enable:
    - staticcheck
    - errcheck
    - gosec
    - govet
    - err113
    # - gocritic
    - exhaustruct
    # - intrange
    # - bodyclose
    # - contextcheck
    # - goconst
    # - noinlineerr
    # - wrapcheck


  settings:
    exhaustruct:
      allow-empty-returns: true
      allow-empty-declarations: 
    staticcheck:
      checks:
        - all
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: true
      exclude-functions:
        - fmt.Println
    govet:
      enable-all: true
