version: "2"
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - err113
    - gosec
    - testpackage
    - contextcheck
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godoclint
    - iface
    - intrange
    - modernize
    - nilerr
    - nilnesserr
    - nilnil
    - recvcheck
    - exhaustruct
  settings:
    exhaustruct:
      allow-empty-returns: false
      allow-empty-declarations: false
      exclude:
        - .*test.*
        - .*domain\.Session.*
        - .*http\.Server.*
        - .*http\.Cookie.*
    staticcheck:
      checks:
        - all
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: true
      exclude-functions:
        - fmt.Println
    govet:
      enable-all: true
